Soen10 patient form
amqkv/minicap pull request #22
Opened 2022-02-21 19:37 UTC by KelvinTrang

# Description

Implements/fixes [SOEN-#10](https://soen390team8.atlassian.net/browse/SOEN-10)

- Create dashboard
- Create forms to fill for patients (frontend and backend)
- Validation for fields in the form
- Create a section for previous days' conditions (frontend and backend)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tests will come afterward

2022-02-21 23:13 UTC, amqkv approved these changes
Small comments for code cleanup. Otherwise good work!

2022-02-21 23:13 UTC, amqkv commented on frontend/__tests__/__mock__/mock.ts
> +// export const DEFAULT_CARD_PATIENT = {
To remove?

2022-02-21 23:13 UTC, amqkv commented on frontend/__tests__/input/input.test.js
> +        // expect(wrapper.find("input").prop("type")).toBe("date");
Same here

2022-02-21 23:13 UTC, amqkv commented on frontend/functions/validation.ts
> +    //return /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/.test(password);
Here too

2022-02-21 23:13 UTC, amqkv commented on frontend/pages/index.tsx
> +      // <>
Here too

2022-02-21 23:21 UTC, stevenvuong00 approved these changes
good work! good job. some console logs here and there to remove

2022-02-21 23:29 UTC, NicholasYip requested changes

2022-02-21 23:29 UTC, NicholasYip commented on backend/controllers/patient-controller.js
> +            console.log("shit")
remove please

2022-02-21 23:29 UTC, NicholasYip commented on backend/controllers/patient-controller.js
> +            const keys = Object.keys(requiredDetails[0]);
could this be moved to another file if this is going to be reused?

2022-02-21 23:29 UTC, NicholasYip commented on backend/controllers/status-controller.js
> +        var day = req.body.statusTime.substring(8, 10);
lit

2022-02-21 23:29 UTC, NicholasYip commented on frontend/__tests__/dashboard.test.js
> +    it("renders a <Dashboard /> component when user is logged in", () => {
could you test the dashboard when the user is of another role?

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/forms/patient-card.tsx
> +            maxW={"400px"}>
does this look good on mobile?

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/forms/patient-form-to-fill.tsx
> +    // console.log(requiredDetails);
remove

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/forms/patient-form-to-fill.tsx
> +                                key={label}
indentation

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/homepage/card.tsx
> +                <Text _hover={{ color: "tomato" }} align={"center"}>
🍅🍅🍅🍅

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/homepage/dashboard-structure.tsx
> +// TODO: add url
forgot to do this?

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/homepage/dashboard.tsx
> +            <Heading paddingLeft={"50px"}>Welcome {userRole} {userName}</Heading>
is this done or not?

2022-02-21 23:29 UTC, NicholasYip commented on frontend/components/inputs/patient-inputs.tsx
> +export default function PatientInputs({ label, units, name, style, error }: InputPatientProps) {
i think this can be renamed to a more generic input, maybe `input-with-units`?

2022-02-21 23:29 UTC, NicholasYip commented on frontend/pages/patient/patient-symptoms-daily.tsx
> +// TODO: fix any
i think this should be done, afaik you already have an interface for this

2022-02-21 23:29 UTC, NicholasYip commented on frontend/pages/patient/patient-symptoms-daily.tsx
> +export async function getServerSideProps(context: any) {
use `import { NextPageContext } from "next";`

2022-02-21 23:29 UTC, NicholasYip commented on frontend/pages/patient/patient-symptoms-daily.tsx
> +            let response: any = await fetch(serverURL + "/patients/getRequiredDetails/" + 3);
should the `3` be replaced by the `userId`?

2022-02-22 01:43 UTC, NicholasYip approved these changes

2022-02-22 03:46 UTC, merged